server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: elevate-banking
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# Logging
logging:
  level:
    root: INFO
    web: OFF
    org.springframework: INFO
    org.apache: OFF
    kafka: OFF
    org.springframework.security: DEBUG


# Docker Configuration
docker:
  host: tcp://192.168.1.128:2375
  api:
    version: 1.41
  connection:
    timeout: 30000
  response:
    timeout: 45000

# Application Security Configuration
app:
  security:
    admin:
      username: admin
      password: 123456
      roles: USER
  docker:
    enabled: true
  frontend:
    url: http://192.168.1.202:3000