spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_ELEVATE_BANKING_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://192.168.1.128:5432/elevate_banking}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:123456}
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 5000
      socket-timeout: 60000
      initialization-fail-timeout: 0
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 60000
      max-lifetime: 1800000
      keepalive-time: 30000
      leak-detection-threshold: 60000
      data-source-properties:
        ssl: false
        sslmode: disable
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
          import_files: data.sql
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: public
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false

  data:
    redis:
      host: ${REDIS_HOST:192.168.1.128}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 60000
      connect-timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

  # Kafka Configuration chi tiết
  kafka:
    bootstrap-servers: 192.168.1.128:9092
    producer:
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        spring.json.trusted.packages: "*"
        security.protocol: PLAINTEXT
        max.block.ms: 10000
        request.timeout.ms: 10000
        retry.backoff.ms: 1000
        retries: 3
    admin:
      properties:
        security.protocol: PLAINTEXT
        request.timeout.ms: 20000
        default.api.timeout.ms: 20000
    properties:
      security.protocol: PLAINTEXT


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: auth
      paths-to-match: /api/v1/auth/**
    - group: accounts
      paths-to-match: /api/v1/accounts/**
    - group: transactions
      paths-to-match: /api/v1/transactions/**

open:
  api:
    title: Elevate Banking API Documentation
    version: 1.0.0
    description: RESTful API documentation for Elevate Banking System
    server:
      url: http://192.168.1.202:8080
      description: Development Server

jwt:
  secret: d0a8c264294f82a0225df5de62105e55a9256889c0ca637b6ae3d737dc06ddec031d4c59c08f8f07571102e5ac317381df36376e7ce32f329e01d025eeab1ad6
  expiration: 2592000000 # 30 days
  refresh-expiration: 86400000000 # 1000 days



